### YamlMime:ManagedReference
items:
- uid: QuickTix.Contracts.Routes
  commentId: N:QuickTix.Contracts.Routes
  id: QuickTix.Contracts.Routes
  children:
  - QuickTix.Contracts.Routes.ApiRoutes
  - QuickTix.Contracts.Routes.ApiRoutes.Admin
  - QuickTix.Contracts.Routes.ApiRoutes.Client
  - QuickTix.Contracts.Routes.ApiRoutes.Crud
  - QuickTix.Contracts.Routes.ApiRoutes.Manager
  - QuickTix.Contracts.Routes.ApiRoutes.Pricing
  - QuickTix.Contracts.Routes.ApiRoutes.Sale
  - QuickTix.Contracts.Routes.ApiRoutes.SaleItem
  - QuickTix.Contracts.Routes.ApiRoutes.Subscription
  - QuickTix.Contracts.Routes.ApiRoutes.Ticket
  - QuickTix.Contracts.Routes.ApiRoutes.User
  - QuickTix.Contracts.Routes.ApiRoutes.Venue
  langs:
  - csharp
  - vb
  name: QuickTix.Contracts.Routes
  nameWithType: QuickTix.Contracts.Routes
  fullName: QuickTix.Contracts.Routes
  type: Namespace
  assemblies:
  - QuickTix.Contracts
references:
- uid: QuickTix.Contracts.Routes.ApiRoutes
  commentId: T:QuickTix.Contracts.Routes.ApiRoutes
  href: QuickTix.Contracts.Routes.ApiRoutes.html
  name: ApiRoutes
  nameWithType: ApiRoutes
  fullName: QuickTix.Contracts.Routes.ApiRoutes
- uid: QuickTix.Contracts.Routes.ApiRoutes.Crud
  commentId: T:QuickTix.Contracts.Routes.ApiRoutes.Crud
  href: QuickTix.Contracts.Routes.ApiRoutes.html
  name: ApiRoutes.Crud
  nameWithType: ApiRoutes.Crud
  fullName: QuickTix.Contracts.Routes.ApiRoutes.Crud
  spec.csharp:
  - uid: QuickTix.Contracts.Routes.ApiRoutes
    name: ApiRoutes
    href: QuickTix.Contracts.Routes.ApiRoutes.html
  - name: .
  - uid: QuickTix.Contracts.Routes.ApiRoutes.Crud
    name: Crud
    href: QuickTix.Contracts.Routes.ApiRoutes.Crud.html
  spec.vb:
  - uid: QuickTix.Contracts.Routes.ApiRoutes
    name: ApiRoutes
    href: QuickTix.Contracts.Routes.ApiRoutes.html
  - name: .
  - uid: QuickTix.Contracts.Routes.ApiRoutes.Crud
    name: Crud
    href: QuickTix.Contracts.Routes.ApiRoutes.Crud.html
- uid: QuickTix.Contracts.Routes.ApiRoutes.User
  commentId: T:QuickTix.Contracts.Routes.ApiRoutes.User
  href: QuickTix.Contracts.Routes.ApiRoutes.html
  name: ApiRoutes.User
  nameWithType: ApiRoutes.User
  fullName: QuickTix.Contracts.Routes.ApiRoutes.User
  spec.csharp:
  - uid: QuickTix.Contracts.Routes.ApiRoutes
    name: ApiRoutes
    href: QuickTix.Contracts.Routes.ApiRoutes.html
  - name: .
  - uid: QuickTix.Contracts.Routes.ApiRoutes.User
    name: User
    href: QuickTix.Contracts.Routes.ApiRoutes.User.html
  spec.vb:
  - uid: QuickTix.Contracts.Routes.ApiRoutes
    name: ApiRoutes
    href: QuickTix.Contracts.Routes.ApiRoutes.html
  - name: .
  - uid: QuickTix.Contracts.Routes.ApiRoutes.User
    name: User
    href: QuickTix.Contracts.Routes.ApiRoutes.User.html
- uid: QuickTix.Contracts.Routes.ApiRoutes.Admin
  commentId: T:QuickTix.Contracts.Routes.ApiRoutes.Admin
  href: QuickTix.Contracts.Routes.ApiRoutes.html
  name: ApiRoutes.Admin
  nameWithType: ApiRoutes.Admin
  fullName: QuickTix.Contracts.Routes.ApiRoutes.Admin
  spec.csharp:
  - uid: QuickTix.Contracts.Routes.ApiRoutes
    name: ApiRoutes
    href: QuickTix.Contracts.Routes.ApiRoutes.html
  - name: .
  - uid: QuickTix.Contracts.Routes.ApiRoutes.Admin
    name: Admin
    href: QuickTix.Contracts.Routes.ApiRoutes.Admin.html
  spec.vb:
  - uid: QuickTix.Contracts.Routes.ApiRoutes
    name: ApiRoutes
    href: QuickTix.Contracts.Routes.ApiRoutes.html
  - name: .
  - uid: QuickTix.Contracts.Routes.ApiRoutes.Admin
    name: Admin
    href: QuickTix.Contracts.Routes.ApiRoutes.Admin.html
- uid: QuickTix.Contracts.Routes.ApiRoutes.Client
  commentId: T:QuickTix.Contracts.Routes.ApiRoutes.Client
  href: QuickTix.Contracts.Routes.ApiRoutes.html
  name: ApiRoutes.Client
  nameWithType: ApiRoutes.Client
  fullName: QuickTix.Contracts.Routes.ApiRoutes.Client
  spec.csharp:
  - uid: QuickTix.Contracts.Routes.ApiRoutes
    name: ApiRoutes
    href: QuickTix.Contracts.Routes.ApiRoutes.html
  - name: .
  - uid: QuickTix.Contracts.Routes.ApiRoutes.Client
    name: Client
    href: QuickTix.Contracts.Routes.ApiRoutes.Client.html
  spec.vb:
  - uid: QuickTix.Contracts.Routes.ApiRoutes
    name: ApiRoutes
    href: QuickTix.Contracts.Routes.ApiRoutes.html
  - name: .
  - uid: QuickTix.Contracts.Routes.ApiRoutes.Client
    name: Client
    href: QuickTix.Contracts.Routes.ApiRoutes.Client.html
- uid: QuickTix.Contracts.Routes.ApiRoutes.Manager
  commentId: T:QuickTix.Contracts.Routes.ApiRoutes.Manager
  href: QuickTix.Contracts.Routes.ApiRoutes.html
  name: ApiRoutes.Manager
  nameWithType: ApiRoutes.Manager
  fullName: QuickTix.Contracts.Routes.ApiRoutes.Manager
  spec.csharp:
  - uid: QuickTix.Contracts.Routes.ApiRoutes
    name: ApiRoutes
    href: QuickTix.Contracts.Routes.ApiRoutes.html
  - name: .
  - uid: QuickTix.Contracts.Routes.ApiRoutes.Manager
    name: Manager
    href: QuickTix.Contracts.Routes.ApiRoutes.Manager.html
  spec.vb:
  - uid: QuickTix.Contracts.Routes.ApiRoutes
    name: ApiRoutes
    href: QuickTix.Contracts.Routes.ApiRoutes.html
  - name: .
  - uid: QuickTix.Contracts.Routes.ApiRoutes.Manager
    name: Manager
    href: QuickTix.Contracts.Routes.ApiRoutes.Manager.html
- uid: QuickTix.Contracts.Routes.ApiRoutes.Ticket
  commentId: T:QuickTix.Contracts.Routes.ApiRoutes.Ticket
  href: QuickTix.Contracts.Routes.ApiRoutes.html
  name: ApiRoutes.Ticket
  nameWithType: ApiRoutes.Ticket
  fullName: QuickTix.Contracts.Routes.ApiRoutes.Ticket
  spec.csharp:
  - uid: QuickTix.Contracts.Routes.ApiRoutes
    name: ApiRoutes
    href: QuickTix.Contracts.Routes.ApiRoutes.html
  - name: .
  - uid: QuickTix.Contracts.Routes.ApiRoutes.Ticket
    name: Ticket
    href: QuickTix.Contracts.Routes.ApiRoutes.Ticket.html
  spec.vb:
  - uid: QuickTix.Contracts.Routes.ApiRoutes
    name: ApiRoutes
    href: QuickTix.Contracts.Routes.ApiRoutes.html
  - name: .
  - uid: QuickTix.Contracts.Routes.ApiRoutes.Ticket
    name: Ticket
    href: QuickTix.Contracts.Routes.ApiRoutes.Ticket.html
- uid: QuickTix.Contracts.Routes.ApiRoutes.Venue
  commentId: T:QuickTix.Contracts.Routes.ApiRoutes.Venue
  href: QuickTix.Contracts.Routes.ApiRoutes.html
  name: ApiRoutes.Venue
  nameWithType: ApiRoutes.Venue
  fullName: QuickTix.Contracts.Routes.ApiRoutes.Venue
  spec.csharp:
  - uid: QuickTix.Contracts.Routes.ApiRoutes
    name: ApiRoutes
    href: QuickTix.Contracts.Routes.ApiRoutes.html
  - name: .
  - uid: QuickTix.Contracts.Routes.ApiRoutes.Venue
    name: Venue
    href: QuickTix.Contracts.Routes.ApiRoutes.Venue.html
  spec.vb:
  - uid: QuickTix.Contracts.Routes.ApiRoutes
    name: ApiRoutes
    href: QuickTix.Contracts.Routes.ApiRoutes.html
  - name: .
  - uid: QuickTix.Contracts.Routes.ApiRoutes.Venue
    name: Venue
    href: QuickTix.Contracts.Routes.ApiRoutes.Venue.html
- uid: QuickTix.Contracts.Routes.ApiRoutes.Subscription
  commentId: T:QuickTix.Contracts.Routes.ApiRoutes.Subscription
  href: QuickTix.Contracts.Routes.ApiRoutes.html
  name: ApiRoutes.Subscription
  nameWithType: ApiRoutes.Subscription
  fullName: QuickTix.Contracts.Routes.ApiRoutes.Subscription
  spec.csharp:
  - uid: QuickTix.Contracts.Routes.ApiRoutes
    name: ApiRoutes
    href: QuickTix.Contracts.Routes.ApiRoutes.html
  - name: .
  - uid: QuickTix.Contracts.Routes.ApiRoutes.Subscription
    name: Subscription
    href: QuickTix.Contracts.Routes.ApiRoutes.Subscription.html
  spec.vb:
  - uid: QuickTix.Contracts.Routes.ApiRoutes
    name: ApiRoutes
    href: QuickTix.Contracts.Routes.ApiRoutes.html
  - name: .
  - uid: QuickTix.Contracts.Routes.ApiRoutes.Subscription
    name: Subscription
    href: QuickTix.Contracts.Routes.ApiRoutes.Subscription.html
- uid: QuickTix.Contracts.Routes.ApiRoutes.Pricing
  commentId: T:QuickTix.Contracts.Routes.ApiRoutes.Pricing
  href: QuickTix.Contracts.Routes.ApiRoutes.html
  name: ApiRoutes.Pricing
  nameWithType: ApiRoutes.Pricing
  fullName: QuickTix.Contracts.Routes.ApiRoutes.Pricing
  spec.csharp:
  - uid: QuickTix.Contracts.Routes.ApiRoutes
    name: ApiRoutes
    href: QuickTix.Contracts.Routes.ApiRoutes.html
  - name: .
  - uid: QuickTix.Contracts.Routes.ApiRoutes.Pricing
    name: Pricing
    href: QuickTix.Contracts.Routes.ApiRoutes.Pricing.html
  spec.vb:
  - uid: QuickTix.Contracts.Routes.ApiRoutes
    name: ApiRoutes
    href: QuickTix.Contracts.Routes.ApiRoutes.html
  - name: .
  - uid: QuickTix.Contracts.Routes.ApiRoutes.Pricing
    name: Pricing
    href: QuickTix.Contracts.Routes.ApiRoutes.Pricing.html
- uid: QuickTix.Contracts.Routes.ApiRoutes.Sale
  commentId: T:QuickTix.Contracts.Routes.ApiRoutes.Sale
  href: QuickTix.Contracts.Routes.ApiRoutes.html
  name: ApiRoutes.Sale
  nameWithType: ApiRoutes.Sale
  fullName: QuickTix.Contracts.Routes.ApiRoutes.Sale
  spec.csharp:
  - uid: QuickTix.Contracts.Routes.ApiRoutes
    name: ApiRoutes
    href: QuickTix.Contracts.Routes.ApiRoutes.html
  - name: .
  - uid: QuickTix.Contracts.Routes.ApiRoutes.Sale
    name: Sale
    href: QuickTix.Contracts.Routes.ApiRoutes.Sale.html
  spec.vb:
  - uid: QuickTix.Contracts.Routes.ApiRoutes
    name: ApiRoutes
    href: QuickTix.Contracts.Routes.ApiRoutes.html
  - name: .
  - uid: QuickTix.Contracts.Routes.ApiRoutes.Sale
    name: Sale
    href: QuickTix.Contracts.Routes.ApiRoutes.Sale.html
- uid: QuickTix.Contracts.Routes.ApiRoutes.SaleItem
  commentId: T:QuickTix.Contracts.Routes.ApiRoutes.SaleItem
  href: QuickTix.Contracts.Routes.ApiRoutes.html
  name: ApiRoutes.SaleItem
  nameWithType: ApiRoutes.SaleItem
  fullName: QuickTix.Contracts.Routes.ApiRoutes.SaleItem
  spec.csharp:
  - uid: QuickTix.Contracts.Routes.ApiRoutes
    name: ApiRoutes
    href: QuickTix.Contracts.Routes.ApiRoutes.html
  - name: .
  - uid: QuickTix.Contracts.Routes.ApiRoutes.SaleItem
    name: SaleItem
    href: QuickTix.Contracts.Routes.ApiRoutes.SaleItem.html
  spec.vb:
  - uid: QuickTix.Contracts.Routes.ApiRoutes
    name: ApiRoutes
    href: QuickTix.Contracts.Routes.ApiRoutes.html
  - name: .
  - uid: QuickTix.Contracts.Routes.ApiRoutes.SaleItem
    name: SaleItem
    href: QuickTix.Contracts.Routes.ApiRoutes.SaleItem.html
